# Site settings
title: Barbara Hui 
email: mail@barbarahui.net 
description: > # this means to ignore newlines until "baseurl:"
   literature :: new media :: mapping :: coding 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://barbarahui.github.io" # the base hostname & protocol for your site
twitter_username: barbarahui 
github_username: barbarahui 

# Build settings
markdown: kramdown
